uart:
  - id: modbus_uart
    tx_pin: GPIO17
    rx_pin: GPIO18
    baud_rate: 9600
    parity: NONE
    stop_bits: 1
    data_bits: 8
    debug:
      direction: BOTH
      dummy_receiver: false

# Modbus protocol configuration
modbus:
  - id: modbus_sabiana
    uart_id: modbus_uart
    send_wait_time: 310ms

# Controller configuration
modbus_controller:
  # Main controller for Sabiana VMC
  - id: sabiana_vmc
    modbus_id: modbus_sabiana
    address: ${modbus_address}
    update_interval: 30s

  # Controller for low frequency operation
  - id: sabiana_vmc_schedules #sabiana_vmc_settings
    modbus_id: modbus_sabiana
    address: ${modbus_address}
    update_interval: never #10min never polling automatically
